name: dbt CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dbt-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt for BigQuery
        run: |
          pip install --upgrade pip
          pip install dbt-bigquery

      - name: Configure dbt profile and keyfile
        env:
          DBT_KEYFILE_JSON: ${{ secrets.DBT_KEYFILE_JSON }}
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_KEYFILE_JSON" > ~/.dbt/keyfile.json

          cat > ~/.dbt/profiles.yml <<EOF
          dbt_felix:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account
                project: dbt-felix
                dataset: dbt_all
                threads: 4
                keyfile: /home/runner/.dbt/keyfile.json
                location: US
          EOF

      - name: Instala dependências da branch do PR (atual)
        run: dbt deps

      - name: Salva o estado da branch main
        run: |
          git fetch origin main
          git checkout origin/main
          dbt deps
          dbt compile --target ci
          mkdir -p state-artifacts
          cp target/manifest.json state-artifacts/manifest.json

      - name: Volta para a branch do PR
        run: |
          git checkout -
          dbt deps
          dbt compile --target ci

      - name: Detect modified models
        id: detect_models
        run: |
          modified_models=$(dbt ls \
            --quiet \
            --target ci \
            --state state-artifacts \
            --select state:modified \
            --resource-type model \
            --output name)
          echo "modified_models<<EOF" >> $GITHUB_OUTPUT
          echo "$modified_models"         >> $GITHUB_OUTPUT
          echo "EOF"                      >> $GITHUB_OUTPUT

      - name: Run models
        if: steps.detect_models.outputs.modified_models != ''
        run: |
          # junta nomes em uma linha
          models=$(echo "${{ steps.detect_models.outputs.modified_models }}" | tr '\n' ' ')
          # para cada modelo, cria "1+<model>+1 "
          selectors=$(for m in $models; do printf "1+%s+1 " "$m"; done)
          echo "Running dbt run for: $selectors"
          dbt run --target ci -m "$selectors"

      - name: Run tests
        if: steps.detect_models.outputs.modified_models != ''
        run: |
          models=$(echo "${{ steps.detect_models.outputs.modified_models }}" | tr '\n' ' ')
          selectors=$(for m in $models; do printf "1+%s+1 " "$m"; done)
          echo "Running dbt test for: $selectors"
          dbt test --target ci -m "$selectors"